# Generated by Django 3.0.2 on 2020-05-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_auto_20200518_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
