# Generated by Django 3.0.2 on 2020-06-04 19:42

import apps.bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_auto_20200603_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to=apps.bboard.models.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
